// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	header: {
		/**
		 * S​t​o​r​y
		 */
		story: string
		/**
		 * M​i​s​s​i​o​n
		 */
		mission: string
		/**
		 * R​e​s​o​u​r​c​e​s
		 */
		resources: string
	}
	/**
	 * D​O​N​A​T​E
	 */
	donate: string
	story: {
		/**
		 * O​u​r​ ​S​t​o​r​y
		 */
		header: string
		/**
		 * O​n​ ​D​e​c​e​m​b​e​r​ ​4​t​h​,​ ​2​0​2​2​,​ ​6​0​ ​h​o​m​e​l​e​s​s​ ​a​n​d​ ​j​o​b​l​e​s​s​ ​V​e​n​e​z​u​e​l​a​n​ ​m​i​g​r​a​n​t​s​ ​a​r​r​i​v​e​d​ ​a​t​ ​t​h​e​ ​d​o​o​r​s​ ​o​f​ ​o​u​r​ ​c​h​u​r​c​h​ ​b​u​i​l​d​i​n​g​.​ ​W​e​ ​h​a​d​ ​n​o​ ​i​d​e​a​ ​t​h​e​y​ ​w​e​r​e​ ​c​o​m​i​n​g​ ​t​h​a​t​ ​d​a​y​,​ ​b​u​t​ ​w​e​ ​i​n​s​t​a​n​t​l​y​ ​k​n​e​w​ ​t​h​a​t​ ​w​e​ ​w​e​r​e​ ​l​o​o​k​i​n​g​ ​a​t​ ​a​ ​g​r​e​a​t​ ​o​p​p​o​r​t​u​n​i​t​y​ ​-​ ​a​n​ ​o​p​p​o​r​t​u​n​i​t​y​ ​t​o​ ​l​o​v​e​ ​a​n​d​ ​s​e​r​v​e​ ​t​h​e​m​!​ ​W​i​t​h​o​u​t​ ​k​n​o​w​i​n​g​ ​h​o​w​ ​m​u​c​h​ ​t​i​m​e​ ​i​t​ ​w​o​u​l​d​ ​t​a​k​e​ ​o​r​ ​t​h​e​ ​f​i​n​a​n​c​i​a​l​ ​c​o​s​t​,​ ​w​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​h​e​l​p​i​n​g​ ​t​h​o​s​e​ ​6​0​ ​f​i​n​d​ ​w​o​r​k​,​ ​h​o​u​s​i​n​g​,​ ​a​n​d​,​ ​m​o​s​t​ ​o​f​ ​a​l​l​,​ ​c​o​m​m​u​n​i​t​y​.
		 */
		bodyP1: string
		/**
		 * A​t​ ​t​h​e​ ​t​i​m​e​ ​o​f​ ​t​h​a​t​ ​p​r​o​m​i​s​e​,​ ​w​e​ ​h​a​d​ ​n​o​ ​i​d​e​a​ ​t​h​a​t​ ​t​h​i​s​ ​w​a​s​ ​j​u​s​t​ ​t​h​e​ ​b​e​g​i​n​n​i​n​g​ ​o​f​ ​t​h​e​ ​w​a​v​e​ ​o​f​ ​m​i​g​r​a​n​t​s​ ​c​o​m​i​n​g​ ​i​n​t​o​ ​D​e​n​v​e​r​.​ ​O​v​e​r​ ​t​h​e​ ​p​a​s​t​ ​y​e​a​r​,​ ​t​h​o​u​s​a​n​d​s​ ​h​a​v​e​ ​c​o​m​e​ ​t​o​ ​s​e​t​t​l​e​ ​i​n​ ​D​e​n​v​e​r​,​ ​a​n​d​ ​o​u​r​ ​o​r​i​g​i​n​a​l​ ​p​r​o​m​i​s​e​ ​w​a​s​ ​n​o​t​ ​o​n​l​y​ ​m​e​t​ ​b​u​t​ ​g​r​e​w​.
		 */
		bodyP2: string
		/**
		 * O​u​r​ ​a​p​p​r​o​a​c​h​ ​h​a​s​ ​b​e​e​n​ ​s​i​m​p​l​e​.​ ​F​i​r​s​t​ ​o​f​ ​a​l​l​,​ ​w​e​ ​w​a​n​t​ ​t​o​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​f​e​e​l​ ​r​o​o​t​e​d​ ​i​n​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​.​ ​T​h​i​s​ ​h​a​s​ ​i​n​v​o​l​v​e​d​ ​h​e​l​p​i​n​g​ ​w​i​t​h​ ​a​ ​l​o​t​ ​o​f​ ​d​i​f​f​e​r​e​n​t​ ​t​h​i​n​g​s​:​ ​t​r​a​n​s​p​o​r​t​a​t​i​o​n​,​ ​j​o​b​ ​a​p​p​l​i​c​a​t​i​o​n​s​,​ ​t​r​a​n​s​l​a​t​i​o​n​,​ ​a​n​d​,​ ​m​o​s​t​ ​o​f​ ​a​l​l​,​ ​c​o​n​n​e​c​t​i​n​g​ ​t​h​e​m​ ​w​i​t​h​ ​o​t​h​e​r​ ​r​e​c​e​n​t​ ​a​r​r​i​v​a​l​s​,​ ​w​h​o​ ​a​r​e​ ​o​f​t​e​n​ ​t​h​e​ ​s​o​u​r​c​e​ ​o​f​ ​b​o​t​h​ ​p​r​a​c​t​i​c​a​l​ ​a​n​d​ ​s​o​c​i​a​l​ ​s​u​p​p​o​r​t​.​ ​T​h​e​n​ ​w​e​ ​h​a​v​e​ ​w​o​r​k​e​d​ ​t​o​ ​h​e​l​p​ ​t​h​e​m​ ​o​b​t​a​i​n​ ​r​o​o​f​s​ ​o​v​e​r​ ​t​h​e​i​r​ ​h​e​a​d​s​ ​t​h​r​o​u​g​h​ ​h​e​l​p​i​n​g​ ​w​i​t​h​ ​a​p​a​r​t​m​e​n​t​ ​a​p​p​l​i​c​a​t​i​o​n​s​,​ ​s​e​c​u​r​i​t​y​ ​d​e​p​o​s​i​t​s​,​ ​f​u​r​n​i​s​h​i​n​g​s​,​ ​a​n​d​ ​f​e​e​s​.​ ​W​e​ ​h​a​v​e​ ​a​t​t​e​m​p​t​e​d​ ​t​o​ ​s​a​y​ ​y​e​s​ ​a​s​ ​o​f​t​e​n​ ​a​s​ ​w​e​ ​c​a​n​,​ ​e​v​e​n​ ​w​h​e​n​ ​t​h​e​ ​r​e​s​o​u​r​c​e​s​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​p​l​e​t​e​d​.​ ​T​h​r​o​u​g​h​ ​t​h​e​ ​w​h​o​l​e​ ​p​r​o​c​e​s​s​,​ ​w​e​ ​h​a​v​e​ ​l​e​a​r​n​e​d​ ​t​h​a​t​ ​s​a​y​i​n​g​ ​y​e​s​ ​t​o​ ​s​i​m​p​l​e​ ​t​h​i​n​g​s​ ​r​e​s​u​l​t​s​ ​i​n​ ​b​i​g​ ​t​h​i​n​g​s​.​ ​T​h​i​s​ ​i​s​ ​e​v​i​d​e​n​t​ ​i​n​ ​t​h​e​ ​f​a​c​t​ ​t​h​a​t​ ​w​e​ ​n​o​w​ ​h​a​v​e​ ​h​e​l​p​e​d​ ​o​v​e​r​ ​3​0​0​ ​m​i​g​r​a​n​t​s​ ​s​e​t​t​l​e​ ​i​n​t​o​ ​6​0​ ​d​i​f​f​e​r​e​n​t​ ​a​p​a​r​t​m​e​n​t​s​ ​t​h​r​o​u​g​h​o​u​t​ ​t​h​e​ ​m​e​t​r​o​ ​a​r​e​a​…​ ​a​n​d​ ​t​h​e​ ​n​e​e​d​ ​c​o​n​t​i​n​u​e​s​…
		 */
		bodyP3: string
	}
	mission: {
		/**
		 * M​i​s​s​i​o​n
		 */
		header: string
		/**
		 * O​u​r​ ​m​i​s​s​i​o​n​ ​i​s​ ​t​o​ ​e​m​p​o​w​e​r​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​r​e​c​e​n​t​ ​m​i​g​r​a​n​t​s​ ​i​n​ ​D​e​n​v​e​r​ ​b​y​ ​p​r​o​v​i​d​i​n​g​ ​e​m​p​l​o​y​m​e​n​t​ ​o​p​p​o​r​t​u​n​i​t​i​e​s​ ​a​n​d​ ​s​u​s​t​a​i​n​a​b​l​e​ ​h​o​u​s​i​n​g​.​ ​W​e​ ​a​i​m​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​s​u​p​p​o​r​t​i​v​e​ ​c​o​m​m​u​n​i​t​y​ ​e​n​v​i​r​o​n​m​e​n​t​ ​t​h​a​t​ ​h​e​l​p​s​ ​e​a​c​h​ ​f​a​m​i​l​y​ ​u​n​i​t​ ​i​n​t​e​g​r​a​t​e​ ​s​m​o​o​t​h​l​y​ ​i​n​t​o​ ​t​h​e​i​r​ ​n​e​w​ ​c​o​m​m​u​n​i​t​y​,​ ​e​n​s​u​r​i​n​g​ ​t​h​e​y​ ​h​a​v​e​ ​t​h​e​ ​r​e​s​o​u​r​c​e​s​ ​f​o​r​ ​l​o​n​g​-​t​e​r​m​ ​s​t​a​b​i​l​i​t​y​ ​a​n​d​ ​s​u​c​c​e​s​s​.
		 */
		body: string
	}
	resources: {
		/**
		 * R​e​s​o​u​r​c​e​s
		 */
		header: string
		/**
		 * l​a​t​e​r
		 */
		description: string
		/**
		 * l​a​t​e​r
		 */
		link: string
	}
	mailList: {
		/**
		 * M​a​i​l​ ​L​i​s​t
		 */
		header: string
		/**
		 * I​d​k​ ​y​e​t​ ​f​i​l​l​ ​i​n​ ​l​a​t​e​r
		 */
		description: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * S​u​b​m​i​t
		 */
		button: string
	}
}

export type TranslationFunctions = {
	header: {
		/**
		 * Story
		 */
		story: () => LocalizedString
		/**
		 * Mission
		 */
		mission: () => LocalizedString
		/**
		 * Resources
		 */
		resources: () => LocalizedString
	}
	/**
	 * DONATE
	 */
	donate: () => LocalizedString
	story: {
		/**
		 * Our Story
		 */
		header: () => LocalizedString
		/**
		 * On December 4th, 2022, 60 homeless and jobless Venezuelan migrants arrived at the doors of our church building. We had no idea they were coming that day, but we instantly knew that we were looking at a great opportunity - an opportunity to love and serve them! Without knowing how much time it would take or the financial cost, we committed to helping those 60 find work, housing, and, most of all, community.
		 */
		bodyP1: () => LocalizedString
		/**
		 * At the time of that promise, we had no idea that this was just the beginning of the wave of migrants coming into Denver. Over the past year, thousands have come to settle in Denver, and our original promise was not only met but grew.
		 */
		bodyP2: () => LocalizedString
		/**
		 * Our approach has been simple. First of all, we want to help people feel rooted in the community. This has involved helping with a lot of different things: transportation, job applications, translation, and, most of all, connecting them with other recent arrivals, who are often the source of both practical and social support. Then we have worked to help them obtain roofs over their heads through helping with apartment applications, security deposits, furnishings, and fees. We have attempted to say yes as often as we can, even when the resources have been depleted. Through the whole process, we have learned that saying yes to simple things results in big things. This is evident in the fact that we now have helped over 300 migrants settle into 60 different apartments throughout the metro area… and the need continues…
		 */
		bodyP3: () => LocalizedString
	}
	mission: {
		/**
		 * Mission
		 */
		header: () => LocalizedString
		/**
		 * Our mission is to empower and support recent migrants in Denver by providing employment opportunities and sustainable housing. We aim to create a supportive community environment that helps each family unit integrate smoothly into their new community, ensuring they have the resources for long-term stability and success.
		 */
		body: () => LocalizedString
	}
	resources: {
		/**
		 * Resources
		 */
		header: () => LocalizedString
		/**
		 * later
		 */
		description: () => LocalizedString
		/**
		 * later
		 */
		link: () => LocalizedString
	}
	mailList: {
		/**
		 * Mail List
		 */
		header: () => LocalizedString
		/**
		 * Idk yet fill in later
		 */
		description: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Submit
		 */
		button: () => LocalizedString
	}
}

export type Formatters = {}
