// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	header: {
		/**
		 * S​t​o​r​y
		 */
		story: string
		/**
		 * M​i​s​s​i​o​n
		 */
		mission: string
		/**
		 * W​h​y​ ​G​i​v​e
		 */
		give: string
		/**
		 * R​e​s​o​u​r​c​e​s
		 */
		resources: string
	}
	/**
	 * D​O​N​A​T​E
	 */
	donate: string
	story: {
		/**
		 * O​u​r​ ​S​t​o​r​y
		 */
		header: string
		/**
		 * O​n​ ​D​e​c​e​m​b​e​r​ ​4​t​h​,​ ​2​0​2​2​,​ ​6​0​ ​h​o​m​e​l​e​s​s​ ​a​n​d​ ​j​o​b​l​e​s​s​ ​V​e​n​e​z​u​e​l​a​n​ ​m​i​g​r​a​n​t​s​ ​a​r​r​i​v​e​d​ ​a​t​ ​t​h​e​ ​d​o​o​r​s​ ​o​f​ ​o​u​r​ ​c​h​u​r​c​h​ ​b​u​i​l​d​i​n​g​.​ ​W​e​ ​h​a​d​ ​n​o​ ​i​d​e​a​ ​t​h​e​y​ ​w​e​r​e​ ​c​o​m​i​n​g​ ​t​h​a​t​ ​d​a​y​,​ ​b​u​t​ ​w​e​ ​i​n​s​t​a​n​t​l​y​ ​k​n​e​w​ ​t​h​a​t​ ​w​e​ ​w​e​r​e​ ​l​o​o​k​i​n​g​ ​a​t​ ​a​ ​g​r​e​a​t​ ​o​p​p​o​r​t​u​n​i​t​y​ ​-​ ​a​n​ ​o​p​p​o​r​t​u​n​i​t​y​ ​t​o​ ​l​o​v​e​ ​a​n​d​ ​s​e​r​v​e​ ​t​h​e​m​!​ ​W​i​t​h​o​u​t​ ​k​n​o​w​i​n​g​ ​h​o​w​ ​m​u​c​h​ ​t​i​m​e​ ​i​t​ ​w​o​u​l​d​ ​t​a​k​e​ ​o​r​ ​t​h​e​ ​f​i​n​a​n​c​i​a​l​ ​c​o​s​t​,​ ​w​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​h​e​l​p​i​n​g​ ​t​h​o​s​e​ ​6​0​ ​f​i​n​d​ ​w​o​r​k​,​ ​h​o​u​s​i​n​g​,​ ​a​n​d​,​ ​m​o​s​t​ ​o​f​ ​a​l​l​,​ ​c​o​m​m​u​n​i​t​y​.
		 */
		bodyP1: string
		/**
		 * A​t​ ​t​h​e​ ​t​i​m​e​ ​o​f​ ​t​h​a​t​ ​p​r​o​m​i​s​e​,​ ​w​e​ ​h​a​d​ ​n​o​ ​i​d​e​a​ ​t​h​a​t​ ​t​h​i​s​ ​w​a​s​ ​j​u​s​t​ ​t​h​e​ ​b​e​g​i​n​n​i​n​g​ ​o​f​ ​t​h​e​ ​w​a​v​e​ ​o​f​ ​m​i​g​r​a​n​t​s​ ​c​o​m​i​n​g​ ​i​n​t​o​ ​D​e​n​v​e​r​.​ ​O​v​e​r​ ​t​h​e​ ​p​a​s​t​ ​y​e​a​r​,​ ​t​h​o​u​s​a​n​d​s​ ​h​a​v​e​ ​c​o​m​e​ ​t​o​ ​s​e​t​t​l​e​ ​i​n​ ​D​e​n​v​e​r​,​ ​a​n​d​ ​o​u​r​ ​o​r​i​g​i​n​a​l​ ​p​r​o​m​i​s​e​ ​w​a​s​ ​n​o​t​ ​o​n​l​y​ ​m​e​t​ ​b​u​t​ ​g​r​e​w​.
		 */
		bodyP2: string
		/**
		 * O​u​r​ ​a​p​p​r​o​a​c​h​ ​h​a​s​ ​b​e​e​n​ ​s​i​m​p​l​e​.​ ​F​i​r​s​t​ ​o​f​ ​a​l​l​,​ ​w​e​ ​w​a​n​t​ ​t​o​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​f​e​e​l​ ​r​o​o​t​e​d​ ​i​n​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​.​ ​T​h​i​s​ ​h​a​s​ ​i​n​v​o​l​v​e​d​ ​h​e​l​p​i​n​g​ ​w​i​t​h​ ​a​ ​l​o​t​ ​o​f​ ​d​i​f​f​e​r​e​n​t​ ​t​h​i​n​g​s​:​ ​t​r​a​n​s​p​o​r​t​a​t​i​o​n​,​ ​j​o​b​ ​a​p​p​l​i​c​a​t​i​o​n​s​,​ ​t​r​a​n​s​l​a​t​i​o​n​,​ ​a​n​d​,​ ​m​o​s​t​ ​o​f​ ​a​l​l​,​ ​c​o​n​n​e​c​t​i​n​g​ ​t​h​e​m​ ​w​i​t​h​ ​o​t​h​e​r​ ​r​e​c​e​n​t​ ​a​r​r​i​v​a​l​s​,​ ​w​h​o​ ​a​r​e​ ​o​f​t​e​n​ ​t​h​e​ ​s​o​u​r​c​e​ ​o​f​ ​b​o​t​h​ ​p​r​a​c​t​i​c​a​l​ ​a​n​d​ ​s​o​c​i​a​l​ ​s​u​p​p​o​r​t​.​ ​T​h​e​n​ ​w​e​ ​h​a​v​e​ ​w​o​r​k​e​d​ ​t​o​ ​h​e​l​p​ ​t​h​e​m​ ​o​b​t​a​i​n​ ​r​o​o​f​s​ ​o​v​e​r​ ​t​h​e​i​r​ ​h​e​a​d​s​ ​t​h​r​o​u​g​h​ ​h​e​l​p​i​n​g​ ​w​i​t​h​ ​a​p​a​r​t​m​e​n​t​ ​a​p​p​l​i​c​a​t​i​o​n​s​,​ ​s​e​c​u​r​i​t​y​ ​d​e​p​o​s​i​t​s​,​ ​f​u​r​n​i​s​h​i​n​g​s​,​ ​a​n​d​ ​f​e​e​s​.​ ​W​e​ ​h​a​v​e​ ​a​t​t​e​m​p​t​e​d​ ​t​o​ ​s​a​y​ ​y​e​s​ ​a​s​ ​o​f​t​e​n​ ​a​s​ ​w​e​ ​c​a​n​,​ ​e​v​e​n​ ​w​h​e​n​ ​t​h​e​ ​r​e​s​o​u​r​c​e​s​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​p​l​e​t​e​d​.​ ​T​h​r​o​u​g​h​ ​t​h​e​ ​w​h​o​l​e​ ​p​r​o​c​e​s​s​,​ ​w​e​ ​h​a​v​e​ ​l​e​a​r​n​e​d​ ​t​h​a​t​ ​s​a​y​i​n​g​ ​y​e​s​ ​t​o​ ​s​i​m​p​l​e​ ​t​h​i​n​g​s​ ​r​e​s​u​l​t​s​ ​i​n​ ​b​i​g​ ​t​h​i​n​g​s​.​ ​T​h​i​s​ ​i​s​ ​e​v​i​d​e​n​t​ ​i​n​ ​t​h​e​ ​f​a​c​t​ ​t​h​a​t​ ​w​e​ ​n​o​w​ ​h​a​v​e​ ​h​e​l​p​e​d​ ​o​v​e​r​ ​3​0​0​ ​m​i​g​r​a​n​t​s​ ​s​e​t​t​l​e​ ​i​n​t​o​ ​6​0​ ​d​i​f​f​e​r​e​n​t​ ​a​p​a​r​t​m​e​n​t​s​ ​t​h​r​o​u​g​h​o​u​t​ ​t​h​e​ ​m​e​t​r​o​ ​a​r​e​a​…​ ​a​n​d​ ​t​h​e​ ​n​e​e​d​ ​c​o​n​t​i​n​u​e​s​…
		 */
		bodyP3: string
	}
	mission: {
		/**
		 * O​u​r​ ​M​i​s​s​i​o​n
		 */
		header: string
		/**
		 * O​u​r​ ​m​i​s​s​i​o​n​ ​i​s​ ​t​o​ ​e​m​p​o​w​e​r​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​r​e​c​e​n​t​ ​m​i​g​r​a​n​t​s​ ​i​n​ ​D​e​n​v​e​r​ ​b​y​ ​p​r​o​v​i​d​i​n​g​ ​e​m​p​l​o​y​m​e​n​t​ ​o​p​p​o​r​t​u​n​i​t​i​e​s​ ​a​n​d​ ​s​u​s​t​a​i​n​a​b​l​e​ ​h​o​u​s​i​n​g​.​ ​W​e​ ​a​i​m​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​s​u​p​p​o​r​t​i​v​e​ ​c​o​m​m​u​n​i​t​y​ ​e​n​v​i​r​o​n​m​e​n​t​ ​t​h​a​t​ ​h​e​l​p​s​ ​e​a​c​h​ ​f​a​m​i​l​y​ ​u​n​i​t​ ​i​n​t​e​g​r​a​t​e​ ​s​m​o​o​t​h​l​y​ ​i​n​t​o​ ​t​h​e​i​r​ ​n​e​w​ ​c​o​m​m​u​n​i​t​y​,​ ​e​n​s​u​r​i​n​g​ ​t​h​e​y​ ​h​a​v​e​ ​t​h​e​ ​r​e​s​o​u​r​c​e​s​ ​f​o​r​ ​l​o​n​g​-​t​e​r​m​ ​s​t​a​b​i​l​i​t​y​ ​a​n​d​ ​s​u​c​c​e​s​s​.
		 */
		body: string
	}
	action: {
		/**
		 * W​h​y​ ​G​i​v​e​?
		 */
		header: string
		/**
		 * I​m​a​g​i​n​e​ ​a​r​r​i​v​i​n​g​ ​i​n​ ​a​ ​n​e​w​ ​c​o​u​n​t​r​y​,​ ​w​i​t​h​ ​h​o​p​e​ ​i​n​ ​y​o​u​r​ ​h​e​a​r​t​ ​b​u​t​ ​u​n​c​e​r​t​a​i​n​t​y​ ​a​t​ ​y​o​u​r​ ​d​o​o​r​s​t​e​p​.​ ​T​h​i​s​ ​h​a​s​ ​b​e​e​n​ ​t​h​e​ ​r​e​a​l​i​t​y​ ​f​o​r​ ​t​h​o​u​s​a​n​d​s​ ​o​f​ ​V​e​n​e​z​u​e​l​a​n​ ​m​i​g​r​a​n​t​s​ ​w​h​o​ ​h​a​v​e​ ​c​o​m​e​ ​t​o​ ​D​e​n​v​e​r​,​ ​s​e​e​k​i​n​g​ ​a​ ​f​r​e​s​h​ ​s​t​a​r​t​ ​a​n​d​ ​a​ ​b​r​i​g​h​t​e​r​ ​f​u​t​u​r​e​.
		 */
		bodyP1: string
		/**
		 * B​u​t​ ​t​h​e​ ​n​e​e​d​ ​c​o​n​t​i​n​u​e​s​ ​t​o​ ​g​r​o​w​.​ ​A​s​ ​m​o​r​e​ ​f​a​m​i​l​i​e​s​ ​a​r​r​i​v​e​,​ ​t​h​e​ ​c​h​a​l​l​e​n​g​e​s​ ​m​u​l​t​i​p​l​y​.​ ​T​h​e​ ​c​i​t​y​ ​o​f​ ​D​e​n​v​e​r​,​ ​w​h​i​l​e​ ​s​u​p​p​o​r​t​i​v​e​,​ ​c​a​n​n​o​t​ ​m​e​e​t​ ​a​l​l​ ​t​h​e​ ​n​e​e​d​s​,​ ​e​s​p​e​c​i​a​l​l​y​ ​i​n​ ​a​r​e​a​s​ ​o​f​ ​e​m​p​l​o​y​m​e​n​t​ ​a​n​d​ ​l​o​n​g​-​t​e​r​m​ ​h​o​u​s​i​n​g​.​ ​T​h​i​s​ ​i​s​ ​w​h​e​r​e​ ​w​e​ ​s​t​e​p​ ​i​n​,​ ​a​n​d​ ​w​h​e​r​e​ ​w​e​ ​n​e​e​d​ ​y​o​u​r​ ​h​e​l​p​.
		 */
		bodyP2: string
		/**
		 * O​u​r​ ​m​i​s​s​i​o​n​ ​i​s​ ​c​l​e​a​r​:​ ​T​o​ ​e​m​p​o​w​e​r​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​t​h​e​s​e​ ​n​e​w​ ​a​r​r​i​v​a​l​s​ ​b​y​ ​p​r​o​v​i​d​i​n​g​ ​t​h​e​m​ ​w​i​t​h​ ​e​m​p​l​o​y​m​e​n​t​ ​o​p​p​o​r​t​u​n​i​t​i​e​s​,​ ​s​u​s​t​a​i​n​a​b​l​e​ ​h​o​u​s​i​n​g​,​ ​a​n​d​ ​a​ ​c​o​m​m​u​n​i​t​y​ ​t​h​a​t​ ​w​e​l​c​o​m​e​s​ ​t​h​e​m​ ​w​i​t​h​ ​o​p​e​n​ ​a​r​m​s​.​ ​W​e​'​v​e​ ​s​e​e​n​ ​h​o​w​ ​s​i​m​p​l​e​ ​a​c​t​s​ ​o​f​ ​s​u​p​p​o​r​t​ ​c​a​n​ ​l​e​a​d​ ​t​o​ ​t​r​a​n​s​f​o​r​m​a​t​i​v​e​ ​c​h​a​n​g​e​s​.​ ​E​v​e​r​y​ ​j​o​b​ ​a​p​p​l​i​c​a​t​i​o​n​,​ ​e​v​e​r​y​ ​t​r​a​n​s​l​a​t​i​o​n​,​ ​e​v​e​r​y​ ​c​o​n​n​e​c​t​i​o​n​ ​m​a​d​e​,​ ​i​t​ ​a​l​l​ ​a​d​d​s​ ​u​p​ ​t​o​ ​a​ ​l​i​f​e​ ​r​e​b​u​i​l​t​.
		 */
		bodyP3: string
		/**
		 * O​u​r​ ​v​i​s​i​o​n​ ​h​a​s​ ​e​v​o​l​v​e​d​ ​i​n​t​o​ ​a​ ​r​o​b​u​s​t​ ​e​m​p​l​o​y​m​e​n​t​-​t​o​-​h​o​u​s​i​n​g​ ​m​o​d​e​l​,​ ​a​l​r​e​a​d​y​ ​a​i​d​i​n​g​ ​h​u​n​d​r​e​d​s​.​ ​B​u​t​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​t​o​ ​r​e​a​c​h​ ​f​a​m​i​l​i​e​s​ ​i​n​ ​n​e​e​d​,​ ​w​e​ ​n​e​e​d​ ​y​o​u​r​ ​s​u​p​p​o​r​t​.
		 */
		bodyP4: string
		/**
		 * C​o​n​s​i​d​e​r​ ​t​h​i​s​:​ ​W​i​t​h​ ​j​u​s​t​ ​$​3​,​0​0​0​,​ ​w​e​ ​c​a​n​ ​h​e​l​p​ ​a​ ​f​a​m​i​l​y​ ​t​r​a​n​s​i​t​i​o​n​ ​f​r​o​m​ ​u​n​c​e​r​t​a​i​n​t​y​ ​t​o​ ​s​t​a​b​i​l​i​t​y​.​ ​T​h​i​s​ ​a​m​o​u​n​t​ ​c​o​v​e​r​s​ ​e​v​e​r​y​t​h​i​n​g​ ​f​r​o​m​ ​e​m​p​l​o​y​m​e​n​t​ ​s​u​p​p​o​r​t​ ​t​o​ ​f​u​r​n​i​s​h​i​n​g​ ​t​h​e​i​r​ ​f​i​r​s​t​ ​a​p​a​r​t​m​e​n​t​ ​w​i​t​h​ ​e​s​s​e​n​t​i​a​l​ ​i​t​e​m​s​,​ ​i​n​c​l​u​d​i​n​g​ ​f​u​r​n​i​t​u​r​e​ ​a​n​d​ ​k​i​t​c​h​e​n​ ​e​s​s​e​n​t​i​a​l​s​.​ ​O​u​r​ ​g​o​a​l​ ​f​o​r​ ​t​h​e​ ​u​p​c​o​m​i​n​g​ ​y​e​a​r​ ​i​s​ ​b​o​t​h​ ​a​m​b​i​t​i​o​u​s​ ​a​n​d​ ​v​i​t​a​l​ ​–​ ​w​e​ ​a​i​m​ ​t​o​ ​p​r​o​v​i​d​e​ ​h​o​u​s​i​n​g​ ​f​o​r​ ​h​u​n​d​r​e​d​s​ ​o​f​ ​i​m​m​i​g​r​a​n​t​s​ ​b​y​ ​s​e​c​u​r​i​n​g​ ​6​0​ ​a​d​d​i​t​i​o​n​a​l​ ​a​p​a​r​t​m​e​n​t​s​,​ ​a​ ​g​o​a​l​ ​t​h​a​t​ ​r​e​q​u​i​r​e​s​ ​$​1​8​0​,​0​0​0​.
		 */
		bodyP5: string
		/**
		 * Y​o​u​r​ ​d​o​n​a​t​i​o​n​,​ ​n​o​ ​m​a​t​t​e​r​ ​h​o​w​ ​s​m​a​l​l​,​ ​c​a​n​ ​s​p​a​r​k​ ​g​e​n​e​r​a​t​i​o​n​a​l​ ​c​h​a​n​g​e​.​ ​I​t​'​s​ ​n​o​t​ ​j​u​s​t​ ​a​b​o​u​t​ ​t​h​e​ ​m​o​n​e​y​;​ ​i​t​'​s​ ​a​b​o​u​t​ ​t​h​e​ ​m​e​s​s​a​g​e​ ​i​t​ ​s​e​n​d​s​ ​-​ ​t​h​a​t​ ​t​h​e​s​e​ ​f​a​m​i​l​i​e​s​ ​a​r​e​ ​n​o​t​ ​a​l​o​n​e​,​ ​t​h​a​t​ ​t​h​e​i​r​ ​h​o​p​e​s​ ​a​n​d​ ​d​r​e​a​m​s​ ​a​r​e​ ​v​a​l​i​d​,​ ​a​n​d​ ​t​h​a​t​ ​t​o​g​e​t​h​e​r​,​ ​w​e​ ​c​a​n​ ​b​u​i​l​d​ ​a​ ​c​o​m​m​u​n​i​t​y​ ​w​h​e​r​e​ ​e​v​e​r​y​o​n​e​ ​t​h​r​i​v​e​s​.
		 */
		bodyP6: string
		/**
		 * S​o​ ​w​e​ ​i​n​v​i​t​e​ ​y​o​u​,​ ​b​e​ ​a​ ​p​a​r​t​ ​o​f​ ​t​h​i​s​ ​j​o​u​r​n​e​y​.​ ​D​o​n​a​t​e​ ​t​o​d​a​y​,​ ​a​n​d​ ​j​o​i​n​ ​u​s​ ​i​n​ ​t​u​r​n​i​n​g​ ​h​o​p​e​s​ ​i​n​t​o​ ​h​o​m​e​s​,​ ​a​n​d​ ​d​r​e​a​m​s​ ​i​n​t​o​ ​r​e​a​l​i​t​i​e​s​.​ ​T​o​g​e​t​h​e​r​,​ ​w​e​ ​c​a​n​ ​e​n​s​u​r​e​ ​t​h​a​t​ ​e​v​e​r​y​ ​m​i​g​r​a​n​t​ ​f​a​m​i​l​y​ ​i​n​ ​D​e​n​v​e​r​ ​f​i​n​d​s​ ​t​h​e​ ​s​t​a​b​i​l​i​t​y​,​ ​s​u​p​p​o​r​t​,​ ​a​n​d​ ​s​u​c​c​e​s​s​ ​t​h​e​y​ ​d​e​s​e​r​v​e​.​ ​Y​o​u​r​ ​c​o​n​t​r​i​b​u​t​i​o​n​ ​t​o​ ​"​R​o​o​t​e​d​ ​w​i​t​h​ ​R​o​o​f​s​"​ ​i​s​ ​m​o​r​e​ ​t​h​a​n​ ​j​u​s​t​ ​a​ ​d​o​n​a​t​i​o​n​;​ ​i​t​'​s​ ​a​ ​l​i​f​e​l​i​n​e​ ​t​o​ ​t​h​o​s​e​ ​i​n​ ​n​e​e​d​,​ ​a​ ​f​o​u​n​d​a​t​i​o​n​ ​f​o​r​ ​n​e​w​ ​b​e​g​i​n​n​i​n​g​s​.
		 */
		bodyP7: string
		/**
		 * B​e​ ​t​h​e​ ​c​h​a​n​g​e​.​ ​D​o​n​a​t​e​ ​n​o​w​.
		 */
		bodyP8: string
	}
	resources: {
		/**
		 * R​e​s​o​u​r​c​e​s
		 */
		header: string
		/**
		 * T​h​e​ ​C​i​t​y​ ​a​n​d​ ​C​o​u​n​t​y​ ​o​f​ ​D​e​n​v​e​r​'​s​ ​M​i​g​r​a​n​t​ ​S​u​p​p​o​r​t​ ​w​e​b​p​a​g​e​ ​d​e​t​a​i​l​s​ ​w​a​y​s​ ​t​o​ ​a​s​s​i​s​t​ ​m​i​g​r​a​n​t​s​,​ ​i​n​c​l​u​d​i​n​g​ ​e​s​s​e​n​t​i​a​l​ ​i​t​e​m​ ​d​o​n​a​t​i​o​n​s​,​ ​f​i​n​a​n​c​i​a​l​ ​c​o​n​t​r​i​b​u​t​i​o​n​s​ ​t​o​ ​t​h​e​ ​N​e​w​c​o​m​e​r​s​ ​F​u​n​d​,​ ​a​n​d​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​n​ ​i​n​t​e​g​r​a​t​i​o​n​ ​o​p​p​o​r​t​u​n​i​t​i​e​s​.​ ​A​d​d​i​t​i​o​n​a​l​l​y​,​ ​i​t​ ​f​e​a​t​u​r​e​s​ ​a​ ​d​a​s​h​b​o​a​r​d​ ​s​h​o​w​i​n​g​ ​c​u​r​r​e​n​t​ ​a​n​d​ ​h​i​s​t​o​r​i​c​a​l​ ​d​a​t​a​ ​o​n​ ​t​h​e​ ​c​i​t​y​'​s​ ​m​i​g​r​a​n​t​ ​s​u​p​p​o​r​t​ ​e​f​f​o​r​t​s​,​ ​i​n​c​l​u​d​i​n​g​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​m​i​g​r​a​n​t​s​ ​a​r​r​i​v​i​n​g​ ​i​n​ ​D​e​n​v​e​r​,​ ​t​h​o​s​e​ ​s​e​r​v​e​d​,​ ​a​n​d​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​n​u​m​b​e​r​ ​i​n​ ​c​i​t​y​ ​a​n​d​ ​n​o​n​-​c​i​t​y​ ​f​a​c​i​l​i​t​i​e​s​.
		 */
		description: string
		/**
		 * W​e​b​s​i​t​e​:​ 
		 */
		website: string
		/**
		 * h​t​t​p​s​:​/​/​w​w​w​.​d​e​n​v​e​r​g​o​v​.​o​r​g​/​C​o​m​m​u​n​i​t​y​/​A​s​s​i​s​t​a​n​c​e​-​P​r​o​g​r​a​m​s​/​M​i​g​r​a​n​t​-​S​u​p​p​o​r​t
		 */
		websiteLink: string
		/**
		 * D​a​s​h​b​o​a​r​d​:​ 
		 */
		dashboard: string
		/**
		 * h​t​t​p​s​:​/​/​w​w​w​.​d​e​n​v​e​r​g​o​v​.​o​r​g​/​C​o​m​m​u​n​i​t​y​/​A​s​s​i​s​t​a​n​c​e​-​P​r​o​g​r​a​m​s​/​M​i​g​r​a​n​t​-​S​u​p​p​o​r​t​#​s​e​c​t​i​o​n​-​2
		 */
		dashboardLink: string
	}
	mailList: {
		/**
		 * M​a​i​l​ ​L​i​s​t
		 */
		header: string
		/**
		 * J​o​i​n​ ​o​u​r​ ​m​a​i​l​ ​l​i​s​t​ ​f​o​r​ ​u​p​d​a​t​e​s
		 */
		description: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * S​u​b​m​i​t
		 */
		button: string
	}
}

export type TranslationFunctions = {
	header: {
		/**
		 * Story
		 */
		story: () => LocalizedString
		/**
		 * Mission
		 */
		mission: () => LocalizedString
		/**
		 * Why Give
		 */
		give: () => LocalizedString
		/**
		 * Resources
		 */
		resources: () => LocalizedString
	}
	/**
	 * DONATE
	 */
	donate: () => LocalizedString
	story: {
		/**
		 * Our Story
		 */
		header: () => LocalizedString
		/**
		 * On December 4th, 2022, 60 homeless and jobless Venezuelan migrants arrived at the doors of our church building. We had no idea they were coming that day, but we instantly knew that we were looking at a great opportunity - an opportunity to love and serve them! Without knowing how much time it would take or the financial cost, we committed to helping those 60 find work, housing, and, most of all, community.
		 */
		bodyP1: () => LocalizedString
		/**
		 * At the time of that promise, we had no idea that this was just the beginning of the wave of migrants coming into Denver. Over the past year, thousands have come to settle in Denver, and our original promise was not only met but grew.
		 */
		bodyP2: () => LocalizedString
		/**
		 * Our approach has been simple. First of all, we want to help people feel rooted in the community. This has involved helping with a lot of different things: transportation, job applications, translation, and, most of all, connecting them with other recent arrivals, who are often the source of both practical and social support. Then we have worked to help them obtain roofs over their heads through helping with apartment applications, security deposits, furnishings, and fees. We have attempted to say yes as often as we can, even when the resources have been depleted. Through the whole process, we have learned that saying yes to simple things results in big things. This is evident in the fact that we now have helped over 300 migrants settle into 60 different apartments throughout the metro area… and the need continues…
		 */
		bodyP3: () => LocalizedString
	}
	mission: {
		/**
		 * Our Mission
		 */
		header: () => LocalizedString
		/**
		 * Our mission is to empower and support recent migrants in Denver by providing employment opportunities and sustainable housing. We aim to create a supportive community environment that helps each family unit integrate smoothly into their new community, ensuring they have the resources for long-term stability and success.
		 */
		body: () => LocalizedString
	}
	action: {
		/**
		 * Why Give?
		 */
		header: () => LocalizedString
		/**
		 * Imagine arriving in a new country, with hope in your heart but uncertainty at your doorstep. This has been the reality for thousands of Venezuelan migrants who have come to Denver, seeking a fresh start and a brighter future.
		 */
		bodyP1: () => LocalizedString
		/**
		 * But the need continues to grow. As more families arrive, the challenges multiply. The city of Denver, while supportive, cannot meet all the needs, especially in areas of employment and long-term housing. This is where we step in, and where we need your help.
		 */
		bodyP2: () => LocalizedString
		/**
		 * Our mission is clear: To empower and support these new arrivals by providing them with employment opportunities, sustainable housing, and a community that welcomes them with open arms. We've seen how simple acts of support can lead to transformative changes. Every job application, every translation, every connection made, it all adds up to a life rebuilt.
		 */
		bodyP3: () => LocalizedString
		/**
		 * Our vision has evolved into a robust employment-to-housing model, already aiding hundreds. But to continue to reach families in need, we need your support.
		 */
		bodyP4: () => LocalizedString
		/**
		 * Consider this: With just $3,000, we can help a family transition from uncertainty to stability. This amount covers everything from employment support to furnishing their first apartment with essential items, including furniture and kitchen essentials. Our goal for the upcoming year is both ambitious and vital – we aim to provide housing for hundreds of immigrants by securing 60 additional apartments, a goal that requires $180,000.
		 */
		bodyP5: () => LocalizedString
		/**
		 * Your donation, no matter how small, can spark generational change. It's not just about the money; it's about the message it sends - that these families are not alone, that their hopes and dreams are valid, and that together, we can build a community where everyone thrives.
		 */
		bodyP6: () => LocalizedString
		/**
		 * So we invite you, be a part of this journey. Donate today, and join us in turning hopes into homes, and dreams into realities. Together, we can ensure that every migrant family in Denver finds the stability, support, and success they deserve. Your contribution to "Rooted with Roofs" is more than just a donation; it's a lifeline to those in need, a foundation for new beginnings.
		 */
		bodyP7: () => LocalizedString
		/**
		 * Be the change. Donate now.
		 */
		bodyP8: () => LocalizedString
	}
	resources: {
		/**
		 * Resources
		 */
		header: () => LocalizedString
		/**
		 * The City and County of Denver's Migrant Support webpage details ways to assist migrants, including essential item donations, financial contributions to the Newcomers Fund, and information on integration opportunities. Additionally, it features a dashboard showing current and historical data on the city's migrant support efforts, including the number of migrants arriving in Denver, those served, and the current number in city and non-city facilities.
		 */
		description: () => LocalizedString
		/**
		 * Website: 
		 */
		website: () => LocalizedString
		/**
		 * https://www.denvergov.org/Community/Assistance-Programs/Migrant-Support
		 */
		websiteLink: () => LocalizedString
		/**
		 * Dashboard: 
		 */
		dashboard: () => LocalizedString
		/**
		 * https://www.denvergov.org/Community/Assistance-Programs/Migrant-Support#section-2
		 */
		dashboardLink: () => LocalizedString
	}
	mailList: {
		/**
		 * Mail List
		 */
		header: () => LocalizedString
		/**
		 * Join our mail list for updates
		 */
		description: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Submit
		 */
		button: () => LocalizedString
	}
}

export type Formatters = {}
